# One of the reasons of not including this into testing workflow is https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches

name: Publish Test Results

on:
  workflow_run:
    workflows: [Build and test on multiple platforms]
    types:
      - completed
permissions: {}

env:
  CI_CD_SHA: 339ac5bb2df2a801747537ca6956fa4114a63dd9
  PUBLISH_ACTION_SHA: ca89ad036b5fcd524c1017287fb01b5139908408

jobs:
  dummy:
    name: "Dummy job"
    # This job runs only if the PR is not from a fork to prevent linking
    runs-on: ubuntu-latest

    steps:
    - name: Print the entire event payload
      run: cat $GITHUB_EVENT_PATH && echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  publish-test-results:
    name: "Publish Overall Tests Results"
    if: github.event.workflow_run.conclusion != 'skipped'
    runs-on: ubuntu-latest

    permissions:
      checks: write

      # needed unless run with comment_mode: off
      pull-requests: write

      # required by download step to access artifacts API
      actions: read

    steps:
      - name: Print the entire event payload
        run: cat $GITHUB_EVENT_PATH && echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e
        with:
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish Test Results to PR
        if: github.event.workflow_run.event == 'repository_dispatch' && github.event.workflow_run.event_payload.event_type == 'test_pr'
        uses: EnricoMi/publish-unit-test-result-action@${{ env.PUBLISH_ACTION_SHA }}
        with:
          files: "${{ env.TESTS_ARTIFACT_NAME }}/**/*.xml"
          report_individual_runs: true
          compare_to_earlier_commit: true  # TODO: check if this comparison work after merge to master
          event_file: pull_event_file/event.json
          event_name: "pull_request"
          # This could be used for files annotation, but Boost JUNIT output is insufficient for it (no file, line properties)
          # test_file_prefix: "+test/"
          # check_run_annotations_branch: "*"


  compare-results-with-master:
    name: Compare Results with Master
    if: github.event.workflow_run.conclusion != 'skipped'
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Get last artifact ID from master branch
        id: get-master-artifact-id
        run: |
          workflow_run_id=$(gh api repos/${{ github.repository }}/actions/runs --jq '.workflow_runs[] | select(.head_branch=="master") | .id' | head -1)
          artifact_id=$(gh api repos/${{ github.repository }}/actions/runs/$workflow_run_id/artifacts --jq '.artifacts[] | select(.name=="test-results") | .id' | head -1)

          echo "artifact-id=$artifact_id" >> "$GITHUB_OUTPUT"

      - name: Download test artifact from master
        id: download-master-tests
        if: steps.get-master-artifact-id.artifact-id != ''
        run: |
          master_artifact_archieve=$(realpath ${{ github.workspace }}/../master_artifact.zip)
          master_artifact_dir=$(realpath ${{ github.workspace }}/../master_test_results)
          gh api repos/${{ github.repository }}/actions/artifacts/${{ steps.get-master-artifact-id.artifact-id }}/zip --output $master_artifact_archieve
          unzip $master_artifact_archieve -d $master_artifact_dir
          echo "unzipped-result=$master_artifact_dir" >> "$GITHUB_OUTPUT"

      - name: Download test results artifact
        id: download-test-results
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/../current_test_results
          name: ${{ env.TESTS_ARTIFACT_NAME }}

      - name: List all test files
        run: find ${{ steps.download-test-results.outputs.download-path }}

      - name: Checkout CI/CD repository
        uses: actions/checkout@v4
        with:
          repository: x-mass/ci_cd
          ref: ${{ env.CI_CD_SHA }}
          path: .ci_cd

      - name: Run differ
        id: differ
        working-directory: .ci_cd
        run: |
          # Reporter could proccess only relative paths
          prev_results_dir="${{ steps.download-master-tests.outputs.unzipped-result }}"
          if [ -z "$prev_results_dir" ]; then
            prev_results_dir="$(realpath ${{ github.workspace }}/../empty_dir)"
            mkdir $prev_results_dir
          fi
          diff_output_dir=$(realpath ${{ github.workspace }}/diff_output)
          python get_tests_diff.py \
            ${{ steps.download-test-results.outputs.download-path }} \
            $prev_results_dir \
            $diff_output_dir
          echo "diff-output-dir=$diff_output_dir" >> "$GITHUB_OUTPUT"

      - name: Display structure of diffed files
        run: ls ${{ steps.differ.outputs.diff-output-dir }} -R

      - name: Publish Modified or Added Tests
        uses: EnricoMi/publish-unit-test-result-action@${{ env.PUBLISH_ACTION_SHA }}
        with:
          check_name: Modified or Added Tests Compared to Master
          files: "diff_output/modified_or_added/**/*.xml"
          report_individual_runs: true
          comment_mode: off
          fail_on: nothing

      - name: Publish Removed Tests
        uses: EnricoMi/publish-unit-test-result-action@${{ env.PUBLISH_ACTION_SHA }}
        with:
          check_name: Removed Tests Compared to Master
          files: "diff_output/removed/**/*.xml"
          report_individual_runs: true
          comment_mode: off
          fail_on: nothing
